CREATE TABLE IF NOT EXISTS players (
    id SERIAL PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    rating INT NOT NULL
);

CREATE TABLE IF NOT EXISTS games (
    id SERIAL PRIMARY KEY,
    player1 TEXT NOT NULL REFERENCES players(name),
    player2 TEXT NOT NULL REFERENCES players(name),
    moves TEXT[] DEFAULT '{}'
);

CREATE TABLE IF NOT EXISTS decks (
    id SERIAL PRIMARY KEY,
    deck_id VARCHAR(255) UNIQUE NOT NULL,
    cards JSONB NOT NULL
);
